### PR TITLE
[mx]Translation-initial

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
Quick questions David Sensei; what would be your original pronunciation for
Ah, and I wonder if this is going to be the complete name for Shichimi's
place? My dilemma is that the word is identical to the exclamation "ah!"
commonly used in mexican-spanish, I am thinking on giving it an extra
letter but would rather ask you first, I don't know if is meant to sound
"A" or "AH" as in "has", or different.

**Comment by Deevad** [comment]
Hi @RJQuiralta ; Yes, it's identical to the exclamation "ah" alone, or just the letter 'A'. Shichimi place will be the Land of the Setting Moons ( a pun for the well known way to call Japan in Europe as "the Land of the Rising Sun" ), 'Ah' is her magic school. The wiki now has more info about 'Ah' if you are curious :) http://www.peppercarrot.com/en/static8/wiki&page=Magic-System  ;  all magic name finish by 'Ah' ; 'Ah' is a sort of missing word of magic, only the end extension remains.

**Comment by ghost** [comment]
Got it, I think I found now a better approach, I think some symbol on the word would make it differ from the expression, :D Let me experiment and would come back with an updated translation!

**Comment by Deevad** [comment]
A symbol could work! good idea.

**Pull request merged**
